version: '3.9'

services: 
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 4000:5000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo_db

volumes:
    mongo_db:      
    